feat: ibus use wayland protocol communication
linuxdeepin/deepin-im pull request #104
Opened 2023-12-15 01:55 UTC by dengbo11

ibus use wayland protocol communication

Log:

2024-01-05 05:25 UTC, zsien requested changes

2024-01-05 05:25 UTC, zsien commented on src/wladdonsbase/inputmethodv1/shm_open_anon.h
common 里有 shm_open_anon 了，不需要再用这个

2024-01-05 07:22 UTC, dengbo11 commented on src/wladdonsbase/inputmethodv1/shm_open_anon.h
done

2024-01-11 05:29 UTC, zsien requested changes

2024-01-11 05:29 UTC, zsien commented on src/wladdonsbase/inputmethodv1/ZwpInputMethodContextV1.cpp
> +    if (keyboardGrabV1_) {
多余的判断

2024-01-11 05:29 UTC, zsien commented on src/wladdonsbase/InputMethodContextV1.cpp
>  void InputMethodContextV1::sendActivate()
这个应该放 input method 而不是 input method context 里

2024-01-11 05:29 UTC, zsien commented on src/wladdonsbase/InputMethodContextV1.cpp
> +void InputMethodContextV1::sendDeactivate()
这个也不应该放 input method context 里

2024-01-11 05:29 UTC, zsien commented on src/wladdonsbase/inputmethodv1/Type.h
>      {
add 可以改个名，因为并不能添加多个

2024-01-11 05:29 UTC, zsien commented on src/wladdonsbase/InputMethodContextV1.h
> +typedef std::function<void(uint32_t serial, const char *text)> commitCb;
```suggestion
typedef std::function<void(uint32_t serial, const char *text)> CommitCb;
```

2024-01-11 05:29 UTC, zsien commented on src/wladdonsbase/inputmethodv1/ZwpInputMethodContextV1.cpp
> +    if (inputmethodV1_ && inputmethodV1_->commitCallback_) {
inputmethodV1_ 多余的判断，构造函数传入

2024-01-12 05:32 UTC, zsien requested changes

2024-01-12 05:32 UTC, zsien commented on src/addons/ibus/IBusProxy.cpp
> +        im->inputMethodContextV1CommitCallback_ =
跟 220 重复

2024-01-12 05:32 UTC, zsien commented on src/wladdonsbase/inputmethodv1/Type.h
> +    void addClientByID(struct wl_client *client, uint32_t id)
这个并不是 add client，直接叫 init 吧，然后把原来的 init 叫 global

2024-01-12 05:36 UTC, dengbo11 commented on src/addons/ibus/IBusProxy.cpp
> +        im->inputMethodContextV1CommitCallback_ =
Done

2024-01-12 05:36 UTC, dengbo11 commented on src/wladdonsbase/inputmethodv1/Type.h
> +    void addClientByID(struct wl_client *client, uint32_t id)
Done

2024-01-12 05:38 UTC, zsien approved these changes

2024-01-12 05:41 UTC, merged